import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect } from "react";
import { LoginButton } from "@/components/login-button";

export default function Home() {
  const { data: session } = useSession();
  useEffect(() => {
    const eventSource = new EventSource(`/api/sse`, {
      withCredentials: true,
    });
    eventSource.onopen = () => {
      console.log("open");
    };
    eventSource.onmessage = (e) => {
      console.log(e.data);
    };
    eventSource.onerror = (e) => {
      console.log(e);
      eventSource.close();
    };

    return () => {
      eventSource.close();
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginButton />

      <main className={styles.main}>
        <h1 className={styles.title}>My Blog</h1>
        <div className={styles.row}>
          <div className={styles.blogCard}>
            <div className={styles.blogCardContent}>
              <h2>Nexjs for Beginers</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam, quidem.
              </p>

              <a href="/blog1">Read More</a>
            </div>
          </div>
          <div className={styles.blogCard}>
            <div className={styles.blogCardContent}>
              <h2>Django Full Course</h2>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam, quidem.
              </p>

              <a href="/blog1">Read More</a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
